### ISSUE TITLE
Build the sample project error on xcode 6.1.1

### ISSUE THREAD

**Issue by jshek65** [socrata/soda-swift#2]
Hi,

    When I tried to build the sample project on xcode 6.1.1, I got the following errors:

Swift Compiler Error
   Overriding method with selector 'tableView:cellForRowAtIndex:' has incompatible type '(UITableView!, NSIndexPath!) ->UITableViewCell'
  UIRefreshControl? does not have a member named 'addTarget'
  UIRefreshControl? does not have a member named 'endRefreshing'
  UIViewController? does not have a member named 'ParentViewController'
  UILabel? does not have a member named 'text
  QueryViewController.swift

    Any ideas what caused these issues?  

Thanks

**Comment by chrismetcalf** [comment]
I'll take a look tomorrow, the library may need updating for 6.1.1.

**Comment by chrismetcalf** [comment]
@jshek65 Can you try out the fixes in https://github.com/socrata/soda-swift/tree/updated-xcode-6.1.1? I got everything compiling in XCode 6.1.1 now, with iOS 8.1.

Note I am a novice Swift developer at best. So please double-check it works for you. :+1:

**Comment by chrismetcalf** [comment]
I'm also downloading XCode 6.2 now, to try that out.

**Comment by chrismetcalf** [comment]
Yep, works on 6.2 as well. I'll leave this open for a couple of days and if I don't hear anything I'll close it and merge to master.
