### ISSUE TITLE
Swift 2 errors

### ISSUE THREAD

**Issue by iyepes** [socrata/soda-swift#5]
I just migrated to XCode 7 and now in SODAClient.swift line 89 I'm receiving a compiler error of Type of expression is ambiguous without more context.  I have no idea how to solve it.

                // Give up if there was a net error
            if reqError != nil {
                syncCompletion(.Error (reqError))
                return
            }

There were also two more compiler errors that I was able to silence, even though I don't know if they are going to work.

In SODAClient.swift 

                Replacing syncCompletion(.Error (NSError())) 
by

                syncCompletion(.Error (NSError(domain: "SODA", code: 0, userInfo: nil)))
                
And in MapViewController

        // Clear old annotations
        if mapView.annotations.count > 0 {
            let ex = mapView.annotations
            mapView.removeAnnotations(ex)
        }

**Comment by iyepes** [comment]
I solved it changing code to

            if let error = reqError {
                syncCompletion(.Error (error))
                return
            }

As long as I'm using the other edits they are working. You can see the code here.

https://github.com/iyepes/SFMobileFood/tree/master/SODAKit

**Comment by chrismetcalf** [comment]
@iyepes I think I fixed the issues in https://github.com/socrata/soda-swift/commit/4f5b8237742fec84d2a93756156d7af826e72cfa. Can you take a look?

Thanks for your help!

**Comment by iyepes** [comment]
I tested the fork and it worked.

Thanks,

**Comment by chrismetcalf** [comment]
Sweet! I'll merge it in.
