### ISSUE TITLE
stringByAddingPercentEscapesUsingEncoding is deprecated

### ISSUE THREAD

**Issue by iyepes** [socrata/soda-swift#6]
In SODAClient
/// Converts an NSDictionary into a query string.

    private class func paramsToQueryString (params: [String: String]) -> String {
        var s = ""
        var head = ""
        for (key, value) in params {
            let sk = key.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!
            let sv = value.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!
            s += "\(head)\(sk)=\(sv)"
            head = "&"
        }
        return s
    }

**Comment by iyepes** [comment]
I fixed it in this way

    private class func paramsToQueryString (params: [String: String]) -> String {
        var s = ""
        var head = ""
        for (key, value) in params {
            let sk = key.stringByAddingPercentEncodingWithAllowedCharacters(.URLHostAllowedCharacterSet())
            let sv = value.stringByAddingPercentEncodingWithAllowedCharacters(.URLHostAllowedCharacterSet())
            s += head+sk!+"="+sv!
            head = "&"
        }
        return s
    }

**Comment by chrismetcalf** [comment]
Fixed in a branch, let me know if the other updates for 7.1/2.1 work and I'll merge both in.
